export const mockCompanies = {
	data: [
		{
			id: 1,
			name: 'Cormier, Koepp and Buckridge',
			rut: '02257576-X',
			email: 'abelardo82@example.org',
			phone: '+16783690829',
			status: 'ACTIVE',
		},
		{
			id: 3,
			name: 'Thompson Ltd',
			rut: '15876292-X',
			email: 'gislason.christa@example.org',
			phone: '+19256053453',
			status: 'ACTIVE',
		},
		{
			id: 4,
			name: "O'Reilly, Konopelski and Walter",
			rut: '49615477-X',
			email: 'jarrett.yundt@example.com',
			phone: '+18474995642',
			status: 'INACTIVE',
		},
		{
			id: 6,
			name: 'Waters-Kessler',
			rut: '82137056-X',
			email: 'linwood55@example.net',
			phone: '+15028411687',
			status: 'ACTIVE',
		},
		{
			id: 8,
			name: 'Batz Ltd',
			rut: '76723634-X',
			email: 'kulas.vanessa@example.com',
			phone: '+15718328631',
			status: 'INACTIVE',
		},
		{
			id: 9,
			name: 'Okuneva-Hand',
			rut: '92180373-X',
			email: 'laurine36@example.com',
			phone: '+14793360835',
			status: 'INACTIVE',
		},
		{
			id: 10,
			name: 'Kutch, Wolff and Wiza',
			rut: '08198177-X',
			email: 'boyle.ephraim@example.net',
			phone: '+15749484151',
			status: 'ACTIVE',
		},
	],
	success: true,
	links: {
		first: 'https://example.com/api/back-office/companies?page=1',
		last: 'https://example.com/api/back-office/companies?page=1',
		prev: null,
		next: null,
	},
	message: 'Companies retrieved successfully',
	meta: {
		current_page: 1,
		from: 1,
		last_page: 1,
		links: [
			{
				url: null,
				label: '&laquo; Anterior',
				active: false,
			},
			{
				url: 'https://example.com/api/back-office/companies?page=1',
				label: '1',
				active: true,
			},
			{
				url: null,
				label: 'Siguiente &raquo;',
				active: false,
			},
		],
		path: 'https://example.com/api/back-office/companies',
		per_page: 15,
		to: 7,
		total: 7,
	},
};

export const mockCompany = {
	success: true,
	data: {
		id: 3,
		name: 'Thompson Ltd',
		rut: '15876292-X',
		email: 'gislason.christa@example.org',
		phone: '+19256053453',
		status: 'INACTIVE',
		vehicles: [
			{
				id: 6,
				type: 'Moto',
				brand: 'Nissan',
				model: 'XV',
				patente: 'jacobs',
				status: 'INACTIVE',
			},
			{
				id: 7,
				type: 'Camioneta PickUp',
				brand: 'Ford',
				model: 'XVI',
				patente: 'dickens',
				status: 'INACTIVE',
			},
			{
				id: 8,
				type: 'Camioneta PickUp',
				brand: 'Nissan',
				model: 'XV',
				patente: 'ruecker',
				status: 'INACTIVE',
			},
			{
				id: 9,
				type: 'Mini Camión Abierto',
				brand: 'Toyota',
				model: 'VI',
				patente: 'terry',
				status: 'INACTIVE',
			},
			{
				id: 10,
				type: 'Mini Camión Abierto',
				brand: 'Renault',
				model: 'VI',
				patente: 'hane',
				status: 'INACTIVE',
			},
			{
				id: 11,
				type: 'Camioneta PickUp',
				brand: 'Chevrolet',
				model: 'XVI',
				patente: 'schroeder',
				status: 'INACTIVE',
			},
			{
				id: 12,
				type: 'Mini Camión Abierto',
				brand: 'Nissan',
				model: 'XVIII',
				patente: 'mitchell',
				status: 'INACTIVE',
			},
			{
				id: 13,
				type: 'Camioneta PickUp',
				brand: 'Renault',
				model: 'V',
				patente: 'hane',
				status: 'INACTIVE',
			},
			{
				id: 14,
				type: 'Camión Mudanzas',
				brand: 'Nissan',
				model: 'XI',
				patente: 'bayer',
				status: 'INACTIVE',
			},
			{
				id: 15,
				type: 'Camión Mudanzas',
				brand: 'Chevrolet',
				model: 'VIII',
				patente: 'douglas',
				status: 'INACTIVE',
			},
		],
	},
	message: 'Company retrieved successfully',
};
