export const mockPromoters = {
	data: [
		{
			id: 101,
			first_name: 'Pormotor',
			last_name: 'Testing',
			rut: '16920515',
			email: 'ajstalito@gmail.com',
			phone: '+584249687130',
			status: 'INACTIVE',
		},
		{
			id: 1,
			first_name: 'Jazlyn',
			last_name: 'Stanton',
			rut: '97232694-X',
			email: 'mosciski.birdie@example.net',
			phone: '+18284392695',
			status: 'ACTIVE',
		},
		{
			id: 2,
			first_name: 'Nelle',
			last_name: 'Quitzon',
			rut: '56459241-X',
			email: 'lynch.clay@example.org',
			phone: '+18479147189',
			status: 'INACTIVE',
		},
		{
			id: 3,
			first_name: 'Dewayne',
			last_name: 'Barton',
			rut: '43790125-X',
			email: 'mayer.kole@example.net',
			phone: '+13174181753',
			status: 'INACTIVE',
		},
		{
			id: 4,
			first_name: 'Wanda',
			last_name: 'Kozey',
			rut: '98614320-X',
			email: 'kaden.goldner@example.org',
			phone: '+19163755849',
			status: 'ACTIVE',
		},
		{
			id: 5,
			first_name: 'Elise',
			last_name: 'Hamill',
			rut: '17213667-X',
			email: 'hwiza@example.net',
			phone: '+18788095700',
			status: 'INACTIVE',
		},
		{
			id: 6,
			first_name: 'Cindy',
			last_name: 'Gaylord',
			rut: '62697841-X',
			email: 'elsie77@example.com',
			phone: '+13204161144',
			status: 'ACTIVE',
		},
		{
			id: 7,
			first_name: 'Robin',
			last_name: 'Wehner',
			rut: '95791382-X',
			email: 'jeramy.rutherford@example.org',
			phone: '+16807630882',
			status: 'INACTIVE',
		},
		{
			id: 8,
			first_name: 'Telly',
			last_name: 'Feil',
			rut: '31227497-X',
			email: 'vferry@example.net',
			phone: '+16514187216',
			status: 'INACTIVE',
		},
		{
			id: 9,
			first_name: 'Trace',
			last_name: 'Purdy',
			rut: '21236785-X',
			email: 'hill.jovani@example.com',
			phone: '+13644334701',
			status: 'ACTIVE',
		},
		{
			id: 10,
			first_name: 'Mohamed',
			last_name: 'Kerluke',
			rut: '22597684-X',
			email: 'fgorczany@example.com',
			phone: '+13644603769',
			status: 'INACTIVE',
		},
		{
			id: 11,
			first_name: 'Jamie',
			last_name: 'Bergnaum',
			rut: '54787342-X',
			email: 'xander06@example.org',
			phone: '+16013650351',
			status: 'INACTIVE',
		},
		{
			id: 12,
			first_name: 'Bertrand',
			last_name: 'Kirlin',
			rut: '56082915-X',
			email: 'eileen74@example.net',
			phone: '+12698172240',
			status: 'ACTIVE',
		},
		{
			id: 13,
			first_name: 'Rosalind',
			last_name: 'Hettinger',
			rut: '24718606-X',
			email: 'nfriesen@example.net',
			phone: '+13109361158',
			status: 'ACTIVE',
		},
		{
			id: 14,
			first_name: 'Gaylord',
			last_name: 'Bartoletti',
			rut: '41216697-X',
			email: 'reva.crona@example.com',
			phone: '+14243016877',
			status: 'INACTIVE',
		},
	],
	success: true,
	links: {
		first: 'https://example.com/api/promoters?page=1',
		last: 'https://example.com/api/promoters?page=7',
		prev: null,
		next: 'https://example.com/api/promoters?page=2',
	},
	message: 'Promoters retrieved successfully',
	meta: {
		current_page: 1,
		from: 1,
		last_page: 7,
		links: [
			{
				url: null,
				label: '&laquo; Anterior',
				active: false,
			},
			{
				url: 'https://example.com/api/promoters?page=1',
				label: '1',
				active: true,
			},
			{
				url: 'https://example.com/api/promoters?page=2',
				label: '2',
				active: false,
			},
			{
				url: 'https://example.com/api/promoters?page=3',
				label: '3',
				active: false,
			},
			{
				url: 'https://example.com/api/promoters?page=4',
				label: '4',
				active: false,
			},
			{
				url: 'https://example.com/api/promoters?page=5',
				label: '5',
				active: false,
			},
			{
				url: 'https://example.com/api/promoters?page=6',
				label: '6',
				active: false,
			},
			{
				url: 'https://example.com/api/promoters?page=7',
				label: '7',
				active: false,
			},
			{
				url: 'https://example.com/api/promoters?page=2',
				label: 'Siguiente &raquo;',
				active: false,
			},
		],
		path: 'https://example.com/api/promoters',
		per_page: 15,
		to: 15,
		total: 101,
	},
};

export const mockPromoter = {
	success: true,
	data: {
		id: 7,
		first_name: 'Robin',
		last_name: 'Wehner',
		rut: '95791382-X',
		email: 'jeramy.rutherford@example.org',
		phone: '+16807630882',
		bank_id: 5,
		bank_name: 'Lockman-Luettgen',
		bank_account_type: 'SAVING',
		bank_account_number: '417578128',
		status: 'INACTIVE',
		created_at: '2022-06-22T03:08:55.000000Z',
	},
	message: 'Promoter retrieved successfully',
};
