import { ReactElement } from 'react';
import Head from 'next/head';
import NextLink from 'next/link';
import NextImage from 'next/image';
import { Button } from '@mui/material';
import { NextPageWithLayout } from './_app';
import logo from '../public/imgs/logo/mudy-sin-fondo-oscuro.png';
import NoSidebarLayout from '../src/Layouts/NoSidebarLayout';

const Home: NextPageWithLayout = () => {
	return (
		<>
			<Head>
				<title>Mudy Dashboard</title>
				<meta name='description' content='Generated by Mudy' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div
				style={{
					display: 'grid',
					placeItems: 'center',
					minHeight: '100vh',
				}}
			>
				<div style={{ minWidth: '20vw' }}>
					<NextImage src={logo} layout='responsive' />
					<NextLink href='/login' passHref>
						<Button variant='contained' fullWidth>
							Login
						</Button>
					</NextLink>
				</div>
			</div>
		</>
	);
};

Home.getLayout = function getLayout(page: ReactElement) {
	return <NoSidebarLayout>{page}</NoSidebarLayout>;
};

export default Home;
